# Generated by Django 4.2.5 on 2023-11-10 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Books",
        ),
    ]
