# Generated by Django 4.2.5 on 2023-12-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="cover",
            field=models.ImageField(blank=True, upload_to="covers/"),
        ),
    ]
