# Generated by Django 4.2.5 on 2023-12-22 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_books_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="books",
            options={"permissions": [("special_status", "Can read all books")]},
        ),
    ]
