# Generated by Django 4.2.5 on 2023-12-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_books_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="books",
            index=models.Index(fields=["id"], name="id_index"),
        ),
    ]
